name: Frontend CI

# Gets triggered on commits to main branch as well as all pull requests
on:
 push:
   branches: ["main"]
 pull_request:

jobs:
 build:
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: ./frontend  # Since all our frontend code is there

   steps:
   - uses: actions/checkout@v4
     
   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
       node-version: 22.x
       cache: 'npm'
       cache-dependency-path: ./frontend/package-lock.json

   # Clean install of dependencies
   - run: npm ci
     
   # Verify build and run tests
   - run: npm run build
   - run: npm test
